export const MAIL_MODULE_OPTIONS = 'MAIL_MODULE_OPTIONS';
export const MAIL_INTEGRATION_SERVICE = 'MAIL_INTEGRATION_SERVICE';
export const MAIL_TEMPLATE_ADAPTER = 'MAIL_TEMPLATE_ADAPTER';
export const MAIL_QUEUE_NAME = '_mail';
